name: CI/CD hdev_server to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        id: checkout-code
        uses: actions/checkout@v3

      - name: AWS IAM 사용자 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 리액트 빌드
        run: |
          npm install
          npm run build

      - name: 빌드한 파일 S3에 업로드
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
          bucket-url: ${{ secrets.AWS_S3_BUCKET_URL }}
          source-dir: ./build

      - name: CloudFront 캐시 무력화 처리
        uses: aws-cloudfront-invalidate-action@1.0.0
        with:
          distribution-id: ${{ secrets.AWS_CLOUDFRONT_ID }}
          paths: "/*"
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
